I18n
leichteckig/nuxt-leichteckig pull request #36
Opened 2021-09-18 14:31 UTC by leichteckig

2021-10-30 11:52 UTC, leichteckig commented on content/articles/common-shopware-testing-pitfalls-de.md
> +Aber das ist noch nicht alles. Shopware stellt einige voreingestellte Plugins zur Verfügung, um Sie mit Elpers und Commads zu versorgen:
xD **H**elper

2021-10-30 11:52 UTC, leichteckig commented on content/articles/common-shopware-testing-pitfalls-de.md
> +Um eine bestimmte Funktionalität zu testen, ist es notwendig, ein Ereignis programmatisch auszulösen.
Jupp, ist wohl aus Faulheit noch da

2021-10-30 11:53 UTC, leichteckig commented on content/articles/common-shopware-testing-pitfalls-de.md
> +Um eine bestimmte Funktionalität zu testen, ist es notwendig, ein Ereignis programmatisch auszulösen.
```suggestion
Um eine bestimmte Funktionalität zu testen, ist es notwendig, ein Event programmatisch auszulösen.
```

2021-10-30 11:53 UTC, leichteckig commented on content/articles/common-shopware-testing-pitfalls-de.md
> +### Wie man ein Ereignis auslöst
```suggestion
### Wie man ein Event auslöst
```

2021-10-30 17:29 UTC, leichteckig commented on pages/privacy.vue
> +        <p>{{ $t('privacyIntroduction2') }}</p>
Jo, das könnte man schauen, andererseits sind das ja keine Blogposts als solches. Müssen wir mal ausprobieren. 🙂

2021-10-30 17:56 UTC, leichteckig commented on content/articles/common-shopware-testing-pitfalls-de.md
> +<hint type="error" title="Be cautious!" message="Only use fixed waiting times temporarily, in order to debug. Replace this wait with a dynamic assertion if the
nö

2022-01-17 15:16 UTC, tobiasberge requested changes
Habe jetzt nicht die übersetzten Artikel gelesen, sondern nur die technischen Sachen angeguckt. Sieht cool aus. 👍  Hab eigentlich nur kleine Anmerkungen oder doofe Fragen.

2022-01-17 15:16 UTC, tobiasberge commented on components/LanguagePicker.vue
> +  <div class="language-switch">
Hier heißt es switch, inkonsistent zu picker - dem namen der Komponente an sich.

2022-01-17 15:16 UTC, tobiasberge commented on components/LargeTile.vue
> +      <NuxtLink :to="localePath(localePath({ name: `${slugName}-slug`, params: { slug: article.slug } }))">
LocalePath ception?

2022-01-17 15:16 UTC, tobiasberge commented on pages/blog/_slug.vue
> +  if (currentLocale === "pl") {
Warum ist hier ein special case für "pl"?

2022-01-17 15:16 UTC, tobiasberge commented on pages/blog/_slug.vue
> +        language: opposingLocale(article.language)
Generell versteh ich dieses `opposingLocale` nicht so ganz. Ist das der Fallback, falls es einen Artikel nicht gibt auf deutsch, dass er immer auf englisch geht?

2022-01-17 15:16 UTC, tobiasberge commented on pages/imprint.vue
> +      title: "Imprint and contact",
Ist der code style nicht genau umgekehrt bei den anderen Komponenten?

2022-01-17 15:16 UTC, tobiasberge commented on test/pages/blog/index.spec.js
> +                        return []
![image](https://user-images.githubusercontent.com/8480203/149794666-019c1b25-b731-4433-b986-30342f4641fb.png)

2022-01-17 15:34 UTC, tobiasberge commented on test/pages/blog/index.spec.js
> +                        return []
Nothing to do here. Ich konnte nur nicht widerstehen :D

2022-01-26 21:28 UTC, leichteckig commented on pages/blog/_slug.vue
> +        language: opposingLocale(article.language)
So habe ich das auch verstanden, habe mich an einem Post entlanggehangelt

2022-01-26 21:28 UTC, leichteckig commented on pages/blog/_slug.vue
> +    return {article};
✅

2022-01-26 21:29 UTC, leichteckig commented on test/pages/blog/_slug.spec.js
> +  it.skip('should be a Vue instance', async () => {
jupp

2022-01-26 22:09 UTC, leichteckig commented on components/Footer.vue
> +        :to="localePath('/imprint/')"
i18n

2022-02-06 22:10 UTC, merged